// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Method               string    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string    `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Protocol             string    `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Headers              []*Header `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Id                   string    `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Request) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Headers              []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Id                   string    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode           int32     `protobuf:"varint,4,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "protobuf.Header")
	proto.RegisterType((*Request)(nil), "protobuf.Request")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x49, 0xd2, 0xe9, 0xcc, 0x5c, 0x45, 0x86, 0xbb, 0x90, 0xe0, 0x42, 0x42, 0x57, 0xc1,
	0x45, 0x17, 0xe3, 0x23, 0xb8, 0x71, 0x9d, 0x37, 0x68, 0xcd, 0x95, 0x0e, 0x56, 0x53, 0xf3, 0x23,
	0x8c, 0x2f, 0xe3, 0xab, 0x4a, 0xd3, 0x56, 0x0a, 0x6e, 0x66, 0x95, 0x73, 0x0e, 0x27, 0xdf, 0x3d,
	0x00, 0x5d, 0x8c, 0x43, 0x3d, 0x78, 0x17, 0x1d, 0xee, 0xf2, 0xd3, 0xa6, 0xd7, 0xea, 0x08, 0xe5,
	0x33, 0x35, 0x96, 0x3c, 0x1e, 0x40, 0xbc, 0xd1, 0x59, 0x32, 0xc5, 0xf4, 0xde, 0x8c, 0x12, 0x6f,
	0xa1, 0xfc, 0x6a, 0xfa, 0x44, 0x41, 0x72, 0x25, 0xf4, 0xde, 0xcc, 0xae, 0xfa, 0x61, 0xb0, 0x35,
	0xf4, 0x99, 0x28, 0xc4, 0xb1, 0xf3, 0x4e, 0xb1, 0x73, 0x76, 0xfe, 0x38, 0xbb, 0x91, 0x96, 0x7c,
	0x2f, 0xf9, 0x44, 0x4b, 0xbe, 0xc7, 0x3b, 0x98, 0xae, 0xbe, 0xb8, 0x5e, 0x8a, 0x1c, 0xff, 0x79,
	0x7c, 0x80, 0x6d, 0x97, 0x57, 0x04, 0x59, 0x28, 0xa1, 0xaf, 0x8e, 0x87, 0x7a, 0x59, 0x58, 0x4f,
	0xf3, 0xcc, 0x52, 0x40, 0x84, 0xa2, 0x75, 0xf6, 0x2c, 0x37, 0x8a, 0xe9, 0x6b, 0x93, 0x35, 0xde,
	0x00, 0x3f, 0x59, 0x59, 0x66, 0x2a, 0x3f, 0xd9, 0xea, 0x1b, 0x76, 0x86, 0xc2, 0xe0, 0x3e, 0x02,
	0xad, 0xd9, 0xec, 0x52, 0x36, 0xff, 0xc7, 0x16, 0x0b, 0x1b, 0xef, 0x01, 0x42, 0x6c, 0x62, 0x0a,
	0x4f, 0xce, 0x92, 0x2c, 0x14, 0xd3, 0x1b, 0xb3, 0x4a, 0xda, 0x32, 0xd3, 0x1f, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x99, 0x94, 0xfd, 0x70, 0x01, 0x00, 0x00,
}
